[package]
name = "ansh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dirs = "5.0.0"
serde = "1.0.160"
serde_derive = "1.0.160"
toml = "0.7.3"
